services:
  - type: web
    name: yt-stream
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python yt_server.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
